### ISSUE TITLE
Long runtime (2hrs+) AzOps pull pipeline

### ISSUE THREAD

**Issue by JenniferKlaveren** [Azure/AzOps#826] opened 2023-10-25 14:34 UTC
**Describe the bug**
We are working in a large organisation and have a huge environment. Right now we are seeing that the AzOps Pull pipeline is taking longer than 2 hours to complete. We expect quite a lot of growth in our environment even, so this increasing time will increase even more. Can you try to optimise this to reduce the runtime? We increased runtime to 3 hours as a workaround for this problem. 

**Screenshots**
![image](https://github.com/Azure/AzOps/assets/148986647/54ee41c8-59de-48dc-9695-c850a15a4765)

**Comment by StefanIvemo** [comment] 2023-10-25 14:39
Which version of AzOps are you running?

**Comment by JenniferKlaveren** [comment] 2023-10-25 14:48
The Latest version, so v2.3.0. First we were always running some versions behind to work with a "stable version" but we have increased it now to check if there was any influence on the runtime, which did not seem to be the case.

**Comment by StefanIvemo** [comment] 2023-10-25 14:55
Thanks. Can you also please share what your settings.json looks like?

**Comment by JenniferKlaveren** [comment] 2023-10-25 15:09
`{
    "Version": 1,
    "DynamicTree": {
        "AzOps": {
            "Core.AutoGeneratedTemplateFolderPath": ".",
            "Core.AutoInitialize": true,
            "Core.DefaultDeploymentRegion": "westeurope",
            "Core.EnrollmentAccountPrincipalName": "",
            "Core.ExcludedSubOffer": [
                "AzurePass_2014-09-01",
                "FreeTrial_2014-09-01",
                "AAD_2015-09-01"
            ],
            "Core.ExcludedSubState": [
                "Disabled",
                "Deleted",
                "Warned",
                "Expired"
            ],
            "Core.ExportRawTemplate": false,
            "Core.IgnoreContextCheck": false,
            "Core.InvalidateCache": true,
            "Core.OfferType": "MS-AZR-0017P",
            "Core.PartialMgDiscoveryRoot": [],
            "Core.SkipPolicy": false,
            "Core.SkipResource": true,
            "Core.SkipResourceGroup": true,
            "Core.SkipResourceType": [
                "microsoft.alertsmanagement/smartDetectorAlertRules",
                "Microsoft.PowerPlatform/accounts",
                "Microsoft.PowerPlatform/enterprisePolicies",
                "microsoft.visualstudio/account",
                "Microsoft.VSOnline/plans"
            ],
            "Core.SkipRole": false,
            "Core.SubscriptionsToIncludeResourceGroups": "*",
            "Core.TemplateParameterFileSuffix": ".json",
            "Core.ThrottleLimit": 5,
            "Core.WhatifExcludedChangeTypes":[
                "NoChange",
                "Ignore"
            ]
        },
        "|AzureDevOps": {
            "!Condition": "EnvAzDevPipeline",
            "AzOps.Core.State": "%PIPELINE_WORKSPACE%/root"
        },
        "|GitHub": {
            "!Condition": "EnvGithubAction",
            "AzOps.Core.State": "%GITHUB_WORKSPACE%/root"
        },
        "PSFramework": {
            "Message.Info.Maximum": 3
        }
    }
}`

**Comment by JenniferKlaveren** [comment] 2023-10-25 15:10
![image](https://github.com/Azure/AzOps/assets/148986647/836c71df-5c47-438e-82cd-d9ac06933f53)

**Comment by Jefajers** [comment] 2023-10-31 14:50
Hi @JenniferKlaveren, please reach out to me over email and lets setup a call to get clarity on the ins and outs of the situation and expected behavior's of AzOps.

**Comment by Jefajers** [comment] 2023-11-07 15:31
After discussing this challenge separately I am closing this issue with the following points:

- In large scale environments it becomes important to have more compute cores available when performing the pull operation. AzOps performs a great deal of operations in parallel but they are restricted by the amount of available cores of the runtime. In this scenario ADO [Microsoft-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware) are used and they are restricted to 2 cores resulting in default parallelism (5).

- To overcome the hosted compute restrictions you can use either [Self-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops) or [Azure Virtual Machine Scale Set agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops) with a higher core count sku and then adjust `Core.ThrottleLimit` value in `settings.json`.

Read more about AzOps performance considerations at:
https://github.com/azure/azops/wiki/performance-considerations

**Closed by Jefajers** 2023-11-07 15:31 UTC
Labels: waiting-for-response, triage
